algoritmo "questão_42"
var
   Numero, C, N1: Inteiro
inicio
      //Comando de entrada para o usuário
      Escreva("Digite um valor: ")
      Leia(Numero)
      
      //definição das variaveis
      C <- 0
      N1 <- 0
      
      //comando para repetir
      Enquanto (C <= Numero) faca
               Escreva(N1)
               N1 <- N1 + 1
               C <- C + 1
      FimEnquanto
      
      //Exibir na tela
      Escreva(" Acabou!")
      
fimalgoritmo