algoritmo "questão_93"
var
   contador, i, f, c: inteiro

procedimento Contador()
inicio
      para contador := i ate f passo c faca
           escreva(contador)
      fimpara
fimprocedimento

inicio
      escreva("Informe o inicio: ")
      leia(i)
      
      escreva("Informe o fim: ")
      leia(f)
      
      escreva("Informe o incremento: ")
      leia(c)
      
      Contador()
fimalgoritmo